batch_size: 64
height: 50
learning_rate: 0.001
max_text_length: 5
model_path: Models/202403071001
train_epochs: 300
train_workers: 20
vocab: !!set
  '0': null
  '1': null
  '2': null
  '3': null
  '4': null
  '5': null
  '6': null
  '7': null
  '8': null
  '9': null
  a: null
  b: null
  c: null
  d: null
  e: null
  f: null
  g: null
  h: null
  i: null
  j: null
  k: null
  l: null
  m: null
  n: null
  o: null
  p: null
  q: null
  r: null
  s: null
  t: null
  u: null
  v: null
  w: null
  x: null
  y: null
  z: null
width: 200
